# Generated by Django 4.2.5 on 2023-09-26 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='personalBest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cardio', models.CharField(max_length=200)),
                ('Benchpress', models.CharField(max_length=200)),
                ('Deadlift', models.CharField(max_length=200)),
                ('Squat', models.CharField(max_length=200)),
                ('Shoulderpress', models.CharField(max_length=200)),
            ],
        ),
    ]
